#!/bin/sh
ssh danielsarmiento@159.65.217.63 <<EOF
 cd ~/node-app-tics
 git pull
 npm install --production
 cd ~/node-app-tics/angularfronted
 npm install --production
 ng build
 pm2 restart all
 exit
EOF